
import dotenv from "dotenv";
dotenv.config();

export const generateFromAI = async (userPrompt, options = {}) => {
  const API_KEY = process.env.GEMINI_API_KEY;
  
  if (!API_KEY) {
    throw new Error("GEMINI_API_KEY not configured");
  }

  const { extensionName, description, permissions } = options;

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${API_KEY}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `
You are a professional Chrome Extension Generator.

STRICT RULES:
- Return ONLY valid JSON
- No explanation, no extra text outside JSON
- DO NOT include "icons" or "default_icon" fields
- Generate clean, secure, and functional code
- Follow Chrome extension best practices

Output format:
{
  "manifest": "",
  "content": "",
  "popup_html": "",
  "popup_js": ""
}

Manifest Requirements:
- Must be valid JSON
- Must include:
  - "manifest_version": 3
  - "name": "${extensionName || 'AI Generated Extension'}"
  - "version": "1.0.0"
  - "description": "${description || 'Extension generated by AI'}"
  - "permissions": ${JSON.stringify(permissions || ['activeTab', 'scripting'])}
  - "action": { "default_popup": "popup.html" }
- Include content_scripts only if functionality requires auto execution:
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["content.js"]
    }
  ]

Content Script Requirements:
- Must contain valid JavaScript
- Must NOT overwrite full HTML (no document.body.innerHTML)
- Should perform the functionality requested by user
- Use modern JavaScript practices
- Add error handling where appropriate

Popup Requirements:
- popup_html must include proper UI structure
- popup_js must handle user interactions
- Connect properly with Chrome APIs when needed

Security Guidelines:
- Sanitize all user inputs
- Use contentSecurityPolicy in manifest
- Avoid eval() and similar dangerous functions
- Validate all external data

User Request:
${userPrompt}

Generate a complete, production-ready Chrome extension based on the user's request.
`
              }
            ]
          }
        ]
      })
    }
  );

  if (!response.ok) {
    throw new Error(`AI service error: ${response.status} ${response.statusText}`);
  }

  const data = await response.json();

  console.log("AI Response Status:", data?.candidates?.[0]?.finishReason);

  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error("AI returned empty response");
  }

  // Clean and parse JSON
  const cleanText = text
    .replace(/```json/g, "")
    .replace(/```/g, "")
    .trim();

  try {
    const parsed = JSON.parse(cleanText);
    
    // Validate required fields
    if (!parsed.manifest || !parsed.content) {
      throw new Error("Missing required fields in AI response");
    }

    // Validate manifest structure
    const manifest = typeof parsed.manifest === 'string' 
      ? JSON.parse(parsed.manifest) 
      : parsed.manifest;

    if (!manifest.manifest_version || !manifest.name || !manifest.version) {
      throw new Error("Invalid manifest structure");
    }

    // Ensure manifest is stringified
    parsed.manifest = JSON.stringify(manifest, null, 2);

    return parsed;
  } catch (err) {
    console.log("RAW TEXT:", cleanText);
    if (err instanceof SyntaxError) {
      throw new Error("Invalid JSON from AI");
    }
    throw err;
  }
};